cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, reduce_from_cart,  CartSummaryView

app_name = 'cart'

urlpatterns = [
    path('cart-summary/', CartSummaryView.as_view(), name='cart-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('reduce-from-cart/<slug>/', reduce_from_cart, name='reduce_from_cart')
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from .views import OrderView, AddCouponView

app_name = 'orders'

urlpatterns = [
    path('order/', OrderView.as_view(), name='create-order'),
    path('order/coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
                                        name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, 
                                        name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views
from .views import AllView

app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('items/', AllView.as_view(), name='all_items'),
    path('<slug:category_slug>/', views.item_list, name='item_list_by_category'),
    path('<int:id>/<slug:slug>/', views.item_detail, name='item_detail'),
]

cart/models.py
from django.db import models
from django.conf import settings
from shop.models import Item
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal


class CartItem(models.Model):
    """Model definition for CartItem."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    in_cart = models.BooleanField(default=True)
    quantity = models.IntegerField(default=1)

    class Meta:
        verbose_name = 'CartItem'
        verbose_name_plural = 'CartItems'

    def __str__(self):
        """Unicode representation of CartItem."""
        return f"{self.quantity} of {self.item.name}"

    def get_total_price(self):
        return self.item.price * self.quantity

    def item_final_price(self):
        return self.get_total_price()

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)

    coupon = models.ForeignKey(
        'Coupon', related_name='coupon', on_delete=models.SET_NULL, blank=True, null=True)
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])

    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        #calculate total price of items in cart
        total = sum(cart_item.item_final_price() for cart_item in self.items.all())      
        return total - total * (self.discount / Decimal(100))

    def count(self):
        #counting number of items in cart
        return len(self.items.all())

class Coupon(models.Model):
    code = models.CharField(max_length=50,
                            unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(
                   validators=[MinValueValidator(0),
                               MaxValueValidator(100)])
    active = models.BooleanField()

    def __str__(self):
        return self.code

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View
from django.core.exceptions import ObjectDoesNotExist
from shop.models import Item
from .models import Cart, CartItem
from django.utils import timezone
from django.contrib import messages


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    cart_item, created = CartItem.objects.get_or_create( 
                            item=item,
                            user=request.user,
                            in_cart=True)
    cart_qs = Cart.objects.filter(user=request.user)
    if cart_qs.exists():
        cart = cart_qs[0]
        # checking if item in cart
        if cart.items.filter(item__slug=item.slug).exists():
            cart_item.quantity += 1
            cart_item.save()
            messages.info(request, f"{item.name} quantity was increased.")
            return redirect('cart:cart-summary')
        else:
            cart.items.add(cart_item)
            messages.info(request, f"{item.name} was added to your cart.")
            return redirect('cart:cart-summary')
    else:
        added_date = timezone.now()
        cart = Cart.objects.create(user=request.user, added_date=added_date)
        cart.items.add(cart_item)
        messages.info(request, f"{item.name} was added to your cart.")
        return redirect('cart:cart-summary')


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    cart_qs = Cart.objects.filter(
        user=request.user
    )
    if cart_qs.exists():
        cart = cart_qs[0]
        # check if the item is in the cart
        if cart.items.filter(item__slug=item.slug).exists():
            cart_item = CartItem.objects.filter(
                item=item,
                user=request.user,
                in_cart=True
            )[0]
            cart.items.remove(cart_item)
            cart_item.delete()
            messages.info(request, f"{item.name} was removed from your cart.")
            return redirect('cart:cart-summary')
        else:
            messages.info(request, f"{item.name} was not in your cart")
            return render(request, 'shop/item/item.html', 
                            {'item': item})
    else:
        messages.info(request, "You have item in your cart")
        return render(request, 'shop/item/item.html', 
                            {'item': item})



@login_required
def reduce_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    cart_qs = Cart.objects.filter(
        user=request.user
    )
    if cart_qs.exists():
        cart = cart_qs[0]
        # check if the item is in the cart
        if cart.items.filter(item__slug=item.slug).exists():
            cart_item = CartItem.objects.filter(
                item=item,
                user=request.user,
                in_cart=True
            )[0]
            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart.items.remove(cart_item)
            messages.info(request, f"{item.name} quantity was reduced from your cart.")
            return redirect('cart:cart-summary')
        else:
            messages.info(request, "This item was not in your cart")
            return render(request, 'shop/item/item.html', 
                            {'item': item})
    else:
        messages.info(request, "You do not have an active order")
        return render(request, 'shop/item/item.html', 
                            {'item': item})



class CartSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            cart = Cart.objects.get(user=self.request.user)
            context = {
                'cart': cart
            }
            return render(self.request, 'cart/cart_detail.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")

templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="Cart">
    <h2 style="text-transform: capitalize;">{{ user.username }}  Shopping Cart has 
        {% if cart.count %}
        {{ cart.count }} Item(s)
        {% else %}
         No Item
        {% endif %} </h2>
    <div class="front-row">
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Image</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart.items.all %}
                <tr>    
                    <td>
                        <h4>{{ cart_item.item.name }}</h4>
                    </td>
                    <td>
                        <a href="{{ cart_item.item.get_absolute_url }}">
                            <img src="{% if cart_item.item.image %}{{ cart_item.item.image.url }}{% else %}{% static 'img/empty_img.png' %}{% endif %}">
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'cart:add_to_cart' cart_item.item.slug %}">
                            <i class="fas fa-sort-up"></i>
                        </a>
                        <h4>{{ cart_item.quantity }}</h4>
                        <a href="{% url 'cart:reduce_from_cart' cart_item.item.slug %}">
                            <i class="fas fa-sort-down"></i>
                        </a>
                    </td>
                    <td>
                        <strong>${{ cart_item.item.price }}</strong>
                        <br>
                        <a href="{% url 'cart:remove_from_cart' cart_item.item.slug %}"><i class="far fa-trash-alt">Remove</i></a>
                    </td>
                    <td>
                        <strong>${{ cart_item.get_total_price }}</strong>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="front-row">
        {% if cart.get_total %}
        <div class="total"><h2>TOTAL</h2></div>
        <div class="total"><h2>${{ cart.get_total }}</h2></div>
        <div class="total">
            <a href="{% url 'orders:create-order' %}" class="button">Checkout</a>
        </div>
        {% endif %}
    </div>
    <center><a href="{% url 'shop:item_list' %}">Continue Shopping</a></center>
</div>
    
{% endblock content %}
    