cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, reduce_from_cart,  CartSummaryView

app_name = 'cart'

urlpatterns = [
    path('cart-summary/', CartSummaryView.as_view(), name='cart-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('reduce-from-cart/<slug>/', reduce_from_cart, name='reduce_from_cart')
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import AllView

app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('items/', AllView.as_view(), name='all_items'),
    path('<slug:category_slug>/', views.item_list, name='item_list_by_category'),
    path('<int:id>/<slug:slug>/', views.item_detail, name='item_detail'),
]

templates/base - no header.html
{% load static %}
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Omen - E-shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Eczar:wght@400;600;800&family=Faster+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
</head>
<body>

    {% include 'shop/item/messages.html' %}


        <div class="nav-container">
            <div class="navbar">
                <div class="brand">
                    <img src="{% static 'img/logo.png' %}" width="150px">
                </div>
                <div class="nav">
                    <ul id="menu-items">
                        <li><a href="{% url 'shop:item_list' %}">Home</a></li>
                        <li><a href="{% url 'shop:all_items' %}">Products</a></li>
                        <li><a href="">Contact</a></li>
                        <li><a href="">About</a></li>

                        {% if user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>    
                        {% else %}
                        <li><a href="{% url 'account_login' %}">Login</a></li>
                        {% endif %}
                        
                    </ul>
                </div>
                <a href="{% url 'cart:cart-summary' %}">
                    <i class="fas fa-shopping-cart">
                        {% if user.is_authenticated %}
                            {% if cart.count %}
                                {{ cart.count }}
                            {% else %}
                                0
                            {% endif %}
                        {% else %}
                        {% endif %}
                    </i>
                </a>
            </div>
            <i class="fas fa-bars" onclick="togglemenu()"></i>
            </div>
            {% block storefront %}

            {% endblock storefront %}
        </div>



  {% block categories %}
 
  {% endblock categories %}



  {% block content %}
              
  {% endblock content %}

     <!-- brands -->
    <div class="brands">
        <div class="small-container">
            <div class="front-row">
                <div class="col-5">
                    <img src="{% static 'img/windows.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/apple.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/devices.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/monitor.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/iphone.png' %}">
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <div class="footer">
        <div class="container">
            <div class="front-row">
                <div class="row-1">
                    <h3>TATIOR</h3>
                    <p>High-Tech for All</p>
                </div>
                <div class="row-2">
                    <img src="{% static 'img/logo.png' %}">
                    <h3>Shop Now</h3>
                </div>
                <div class="row-3">
                    <strong>LINKS</strong>
                    <ul>
                        <li>Home</li>
                        <li>Products</li>
                        <li>Contact</li>
                        <li>About</li>
                    </ul>
                </div>
                <div class="row-4">
                    <strong>Follow Us</strong>
                    <ul>
                        <li>Facebook</li>
                        <li>Instagram</li>
                        <li>Youtube</li>
                        <li>Twitter</li>
                    </ul>
                </div>
            </div>
            <p class="copyright">Copyright - E-shop by itzomen</p>
        </div>
    </div>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Omen - E-shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Eczar:wght@400;600;800&family=Faster+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
</head>
<body>

    {% include 'shop/item/messages.html' %}


        <div class="nav-container">
            <div class="navbar">
                <div class="brand">
                    <img src="{% static 'img/logo.png' %}" width="150px">
                </div>
                <div class="nav">
                    <ul id="menu-items">
                        <li><a href="{% url 'shop:item_list' %}">Home</a></li>
                        <li><a href="{% url 'shop:all_items' %}">Products</a></li>
                        <li><a href="">Contact</a></li>
                        <li><a href="">About</a></li>

                        {% if user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>    
                        {% else %}
                        <li><a href="{% url 'account_login' %}">Login</a></li>
                        {% endif %}
                        
                    </ul>
                </div>
                <a href="{% url 'cart:cart-summary' %}">
                    <i class="fas fa-shopping-cart">
                        {% if user.is_authenticated %}
                            {% if cart.count %}
                                {{ cart.count }}
                            {% else %}
                                0
                            {% endif %}
                        {% else %}
                        {% endif %}
                    </i>
                </a>
            </div>
            <i class="fas fa-bars" onclick="togglemenu()"></i>
            </div>
            {% block storefront %}

            {% endblock storefront %}
        </div>



  {% block categories %}
 
  {% endblock categories %}



  {% block content %}
              
  {% endblock content %}

     <!-- brands -->
    <div class="brands">
        <div class="small-container">
            <div class="front-row">
                <div class="col-5">
                    <img src="{% static 'img/windows.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/apple.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/devices.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/monitor.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/iphone.png' %}">
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <div class="footer">
        <div class="container">
            <div class="front-row">
                <div class="row-1">
                    <h3>TATIOR</h3>
                    <p>High-Tech for All</p>
                </div>
                <div class="row-2">
                    <img src="{% static 'img/logo.png' %}">
                    <h3>Shop Now</h3>
                </div>
                <div class="row-3">
                    <strong>LINKS</strong>
                    <ul>
                        <li>Home</li>
                        <li>Products</li>
                        <li>Contact</li>
                        <li>About</li>
                    </ul>
                </div>
                <div class="row-4">
                    <strong>Follow Us</strong>
                    <ul>
                        <li>Facebook</li>
                        <li>Instagram</li>
                        <li>Youtube</li>
                        <li>Twitter</li>
                    </ul>
                </div>
            </div>
            <p class="copyright">Copyright - E-shop by itzomen</p>
        </div>
    </div>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Omen - E-shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Eczar:wght@400;600;800&family=Faster+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
</head>
<body>

    {% include 'shop/item/messages.html' %}

  <div class="header">
        <div class="nav-container">
            <div class="navbar">
                <div class="brand">
                    <img src="{% static 'img/logo.png' %}" width="150px">
                </div>
                <div class="nav">
                    <ul id="menu-items">
                        <li><a class="active" href="{% url 'shop:item_list' %}">Home</a></li>
                        <li><a href="{% url 'shop:all_items' %}">Products</a></li>
                        <li><a href="">Contact</a></li>
                        <li><a href="">About</a></li>
                        
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>    
                        {% else %}
                        <li><a href="{% url 'account_login' %}">Login</a></li>
                        {% endif %}
                        
                    </ul>
                </div>
                <a href="{% url 'cart:cart-summary' %}">
                    <i class="fas fa-shopping-cart">
                        {% if user.is_authenticated %}
                            {% if cart.count %}
                                {{ cart.count }}
                            {% else %}
                                0
                            {% endif %}
                        {% else %}
                        {% endif %}
                    </i>
                </a>
            </div>
            <i class="fas fa-bars" onclick="togglemenu()"></i>
            </div>
            {% block storefront %}

            {% endblock storefront %}
        </div>
  </div>


  {% block categories %}
 
  {% endblock categories %}



  {% block content %}
              
  {% endblock content %}
    
     <!-- brands -->
    <div class="brands">
        <div class="small-container">
            <div class="front-row">
                <div class="col-5">
                    <img src="{% static 'img/windows.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/apple.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/devices.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/monitor.png' %}">
                </div>
                <div class="col-5">
                    <img src="{% static 'img/iphone.png' %}">
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <div class="footer">
        <div class="container">
            <div class="front-row">
                <div class="row-1">
                    <h3>TATIOR</h3>
                    <p>High-Tech for All</p>
                </div>
                <div class="row-2">
                    <img src="{% static 'img/logo.png' %}">
                    <h3>Shop Now</h3>
                </div>
                <div class="row-3">
                    <strong>LINKS</strong>
                    <ul>
                        <li>Home</li>
                        <li>Products</li>
                        <li>Contact</li>
                        <li>About</li>
                    </ul>
                </div>
                <div class="row-4">
                    <strong>Follow Us</strong>
                    <ul>
                        <li>Facebook</li>
                        <li>Instagram</li>
                        <li>Youtube</li>
                        <li>Twitter</li>
                    </ul>
                </div>
            </div>
            <p class="copyright">Copyright - E-shop by itzomen</p>
        </div>
    </div>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>