cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, reduce_from_cart,  CartSummaryView

app_name = 'cart'

urlpatterns = [
    path('cart-summary/', CartSummaryView.as_view(), name='cart-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('reduce-from-cart/<slug>/', reduce_from_cart, name='reduce_from_cart')
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from .views import OrderView, AddCouponView

app_name = 'orders'

urlpatterns = [
    path('order/', OrderView.as_view(), name='create-order'),
    path('order/coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
                                        name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, 
                                        name='admin_order_pdf'),
]

orders/models.py
from django.db import models
from django.conf import settings
from shop.models import Item
from cart.models import Coupon
from django.core.validators import MinValueValidator, MaxValueValidator


class Order(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    city = models.CharField(max_length=20)
    address = models.CharField(max_length=100)

    coupon = models.ForeignKey(
        Coupon , on_delete=models.SET_NULL, blank=True, null=True)
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])
        
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)


    def __str__(self):
        return f'Order {self.id}'

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'
        ordering = ('-created',)

class OrderItems(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    order = models.ForeignKey(Order,
                              related_name='order',
                              on_delete=models.CASCADE)
    order_items = models.ForeignKey(Item,
                              related_name='order_items',
                              on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = 'OrderItems'
        verbose_name_plural = 'OrderItemss'

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order
#from cart.models import Coupon

class OrderForm(forms.ModelForm):
    """Form definition for Order."""

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 
                'email', 'city', 'address']

class CouponForm(forms.Form):
    code = forms.CharField()

orders/views.py
from django.forms.forms import Form
from django.shortcuts import render, redirect
from .models import OrderItems
from cart.models import Cart, Coupon
from .forms import OrderForm, CouponForm
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View
from .tasks import email_order
from django.utils import timezone
#used payments app
from django.urls import reverse
#added for custom admin views
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from .models import Order
#used to generate pdf
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint

@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'orders/admin/order_detail.html',
                            {'order': order})

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
        stylesheets=[weasyprint.CSS(
            settings.STATIC_ROOT + 'css/pdf.css')])
    return response


class OrderView(View):
    def get(self, *args, **kwargs):
        
        cart = Cart.objects.get(user=self.request.user)
        total = cart.get_total()
        items = cart.items.all()
        form = OrderForm()
        coupon_form = CouponForm()
        context = {
            'form': form,
            'coupon_form': coupon_form,
            'items': items,
            'total': total,
        }
        return render(self.request, 'orders/create.html', context)

    def post(self, *args, **kwargs):

        cart = Cart.objects.get(user=self.request.user)
        user = cart.user
        total = cart.get_total()
        items = cart.items.all()

        form = OrderForm(self.request.POST or None)
        if items:
            if form.is_valid():
                order_form = form.save(commit=False)
                order_form.total = total
                order_form.save()
                for item in items:
                    orderitems = OrderItems.objects.create(user=user,
                                            order=order_form,
                                            order_items=item.item,
                                            price=item.item.price,
                                            quantity=item.quantity)
                #delete query set i.e cart
                items.delete()
                # delay to launch the task asynchronously
                email_order.delay(order_form.id)
                # set the order and orderitems id in session
                self.request.session['order_id'] = order_form.id
                # redirect for payment
                messages.info(self.request, f"Your order was created")
                return redirect(reverse('payments:process'))
                # messages.info(request, f"Your order was created")
        else:
            messages.info(self.request, "Add items to cart")
            return redirect('cart:cart-summary')

def get_coupon(request, code):
    now = timezone.now()
    try:
        coupon = Coupon.objects.get(code__iexact=code,
                                        valid_from__lte=now,
                                        valid_to__gte=now,
                                        active=True)
        return coupon
    except Coupon.DoesNotExist:
        messages.info(request, "This coupon does not exist")

class AddCouponView(View):
    def post(self, *args, **kwargs):
        cart = Cart.objects.get(user=self.request.user)

        coupon_form = CouponForm(self.request.POST or None)
        if coupon_form.is_valid():
            code = coupon_form.cleaned_data['code']
            cart.coupon = get_coupon(self.request, code)               
            if cart.coupon:
                cart.discount = cart.coupon.discount
                cart.save()
                self.request.session['coupon_id'] = cart.coupon.id
                messages.success(self.request, "Successfully added coupon")
                messages.info(self.request, f"{cart.coupon.discount}% OFF Coupon")
            
            return redirect('orders:create-order')
           

templates/orders/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    <div class="front-row">
        <div class="col-2">
            <form method="post" class="order-form">
                {{ form.as_p }}
                <p><input type="submit" value="Place order"></p>
                {% csrf_token %}
            </form>
        </div>
        <div class="col-3">
            <h1>Checkout</h1>
            <div class="order-info">
                <h3>Your order</h3>
                <ul>
                {% for item in items %}
                <li>
                {{ item.quantity }}x {{ item.item.name }}
                <span>${{ item.item_final_price }}</span>
                </li>
                {% endfor %}
                </ul>
                <p>Total: ${{ total }}</p>
            </div>
            <br>
            <div class="coupon">
                <h2>Add Coupon</h2>
                <form action="{% url "orders:add-coupon" %}" method="post" class="order-form">
                    {{ coupon_form.as_p }}
                    <p><input type="submit" value="Add Coupon"></p>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
 
 
{% endblock %}

templates/orders/created.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
   <div class="front-row">
    <h1>Thank you</h1>
    <p>Your order has been successfully completed with unique number
    <strong>{{ order.id }}</strong>.
    <br>
    Reach out to us for payment and delivery</p> 
   </div>
{% endblock %}

templates/orders/pdf.html
<html>
<body>
  <h1>E-Shop</h1>
  <h3>Order no. {{ order.id }}</h3>
  <p>
    <span class="secondary">
      {{ order.created|date:"M d, Y" }}
    </span>
  </p>

  <h3>Client Details</h3>
  <h4>Name</h4><p>{{ order.first_name }} {{ order.last_name }}</p>
  <h4>Email</h4><p>{{ order.email }}</p>
  <h4>City</h4><p>{{ order.city }}</p>
  <h4>Address</h4><p>{{ order.address }}</p>

  <h3>Order  Items</h3>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
        {% for item in order.order.all %}
        <tr class="row{% cycle "1" "2" %}">
            <td>{{ item.order_items.name }}</td>
            <td class="num">${{ item.price }}</td>
            <td class="num">{{ item.quantity }}</td>
            <td class="num">${{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      {% if order.coupon %}
      <tr class="total">
        <td colspan="3">{{ order.coupon }} Coupon</td>
        <td class="num">{{ order.discount }}% OFF</td>
      </tr>
      {% endif %}
      <tr class="total">
        <td colspan="3">Total</td>
        <td class="num">${{ order.total }}</td>
      </tr>
    </tbody>
  </table>

  <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
    {% if order.paid %}Paid{% else %}Pending payment{% endif %}
  </span>
</body>
</html>